// src/components/demos/vue/button-group.vue
<script setup lang="ts">
import { ButtonGroup, ButtonGroupItem } from "@/components/ui-vue/button-group";
</script>

<template>
  <ButtonGroup>
    <ButtonGroupItem>Day</ButtonGroupItem>
    <ButtonGroupItem>Week</ButtonGroupItem>
    <ButtonGroupItem>Month</ButtonGroupItem>
  </ButtonGroup>
</template>

// src/components/demos/react/button-group.tsx
import { ButtonGroup, ButtonGroupItem } from "@/components/ui/button-group";

function ButtonGroupDemo() {
  return (
    <ButtonGroup>
      <ButtonGroupItem>Day</ButtonGroupItem>
      <ButtonGroupItem>Week</ButtonGroupItem>
      <ButtonGroupItem>Month</ButtonGroupItem>
    </ButtonGroup>
  );
}

export { ButtonGroupDemo };
