// src/components/demos/vue/combobox.vue
<script setup lang="ts">
import * as combobox from "@zag-js/combobox";
import { ref } from "vue";
import {
  ComboboxRoot,
  ComboboxInput,
  ComboboxTrigger,
  ComboboxContent,
  ComboboxItemGroup,
  ComboboxItem,
  ComboboxItemText,
  ComboboxItemIndicator,
} from "@/components/ui-vue/combobox";

const frameworks = ["React", "Solid", "Vue", "Svelte"];

const state = ref([""]);
const itemsCollection = ref(combobox.collection({ items: frameworks }));

function handleInputChange(details: { inputValue: string }) {
  const query = details.inputValue.toLowerCase();
  itemsCollection.value = combobox.collection({
    items: frameworks.filter((item) => item.toLowerCase().includes(query)),
  });
}

function handleValueChange(details: { value: string[] }) {
  state.value = details.value;
}
</script>

<template>
  <ComboboxRoot
    :value="state"
    :collection="itemsCollection"
    :onInputValueChange="handleInputChange"
    :onValueChange="handleValueChange"
  >
    <ComboboxTrigger />
    <ComboboxContent>
      <ComboboxInput />
      <ComboboxItemGroup>
        <ComboboxItem v-for="item in itemsCollection.items" :key="item" :item="item">
          <ComboboxItemText>{{ item }}</ComboboxItemText>
          <ComboboxItemIndicator />
        </ComboboxItem>
      </ComboboxItemGroup>
    </ComboboxContent>
  </ComboboxRoot>
</template>

// src/components/demos/react/combobox.tsx
import * as combobox from "@zag-js/combobox";
import { useState } from "react";
import {
  ComboboxRoot,
  ComboboxInput,
  ComboboxTrigger,
  ComboboxContent,
  ComboboxItemGroup,
  ComboboxItem,
  ComboboxItemText,
  ComboboxItemIndicator,
} from "@/components/ui/combobox";

const frameworks = ["React", "Solid", "Vue", "Svelte"];

function ComboboxDemo() {
  const [state, setState] = useState([""]);
  const [itemsCollection, setItemsCollection] = useState(() =>
    combobox.collection({ items: frameworks })
  );

  const handleInputChange = (details: { inputValue: string }) => {
    const query = details.inputValue.toLowerCase();
    setItemsCollection(
      combobox.collection({
        items: frameworks.filter((item) => item.toLowerCase().includes(query)),
      })
    );
  };

  return (
    <ComboboxRoot
      value={state}
      collection={itemsCollection}
      onInputValueChange={handleInputChange}
      onValueChange={(details) => setState(details.value)}
    >
      <ComboboxTrigger />
      <ComboboxContent>
        <ComboboxInput />
        <ComboboxItemGroup>
          {itemsCollection.items.map((item) => (
            <ComboboxItem key={item} item={item}>
              <ComboboxItemText>{item}</ComboboxItemText>
              <ComboboxItemIndicator />
            </ComboboxItem>
          ))}
        </ComboboxItemGroup>
      </ComboboxContent>
    </ComboboxRoot>
  );
}

export { ComboboxDemo };
