// src/components/demos/vue/daterangepicker.vue
<script setup lang="ts">
import {
  DatePickerRoot,
  DatePickerControl,
  DatePickerContent,
  DatePickerCalendar,
} from "@/components/ui-vue/date-picker";
</script>

<template>
  <DatePickerRoot selectionMode="range">
    <DatePickerControl />
    <DatePickerContent>
      <DatePickerCalendar />
    </DatePickerContent>
  </DatePickerRoot>
</template>

// src/components/demos/react/daterangepicker.tsx
import {
  DatePickerRoot,
  DatePickerControl,
  DatePickerContent,
  DatePickerCalendar,
} from "@/components/ui/date-picker";

function DaterangepickerDemo() {
  return (
    <DatePickerRoot selectionMode="range">
      <DatePickerControl />
      <DatePickerContent>
        <DatePickerCalendar />
      </DatePickerContent>
    </DatePickerRoot>
  );
}

export { DaterangepickerDemo };
