// src/components/demos/vue/menu.vue
<script setup lang="ts">
import { MenuRoot, MenuTrigger, MenuContent, MenuItem } from "@/components/ui-vue/menu";
import { PenLine, FilePenLine, CopySlash, Eraser, FileUp } from "@lucide/vue";
</script>

<template>
  <MenuRoot>
    <MenuTrigger class="w-56">
      <PenLine class="size-4 me-2.5" /> Actions
    </MenuTrigger>
    <MenuContent>
      <MenuItem value="edit">
        <FilePenLine class="size-4 me-2.5" /> Edit
      </MenuItem>
      <MenuItem value="duplicate">
        <CopySlash class="size-4 me-2.5" /> Duplicate
      </MenuItem>
      <MenuItem value="delete">
        <Eraser class="size-4 me-2.5" /> Delete
      </MenuItem>
      <MenuItem value="export">
        <FileUp class="size-4 me-2.5" /> Export...
      </MenuItem>
    </MenuContent>
  </MenuRoot>
</template>

// src/components/demos/react/menu.tsx
import { MenuRoot, MenuTrigger, MenuContent, MenuItem } from "@/components/ui/menu";
import { PenLine, FilePenLine, CopySlash, Eraser, FileUp } from "lucide-react";

function MenuDemo() {
  return (
    <MenuRoot>
      <MenuTrigger className="w-56">
        <PenLine className="size-4 me-2.5" /> Actions
      </MenuTrigger>
      <MenuContent>
        <MenuItem value="edit">
          <FilePenLine className="size-4 me-2.5" /> Edit
        </MenuItem>
        <MenuItem value="duplicate">
          <CopySlash className="size-4 me-2.5" /> Duplicate
        </MenuItem>
        <MenuItem value="delete">
          <Eraser className="size-4 me-2.5" /> Delete
        </MenuItem>
        <MenuItem value="export">
          <FileUp className="size-4 me-2.5" /> Export...
        </MenuItem>
      </MenuContent>
    </MenuRoot>
  );
}

export { MenuDemo };
