// src/components/demos/vue/number-input.vue
<script setup lang="ts">
import {
  NumberInputRoot,
  NumberInputLabel,
  NumberInputControl,
} from "@/components/ui-vue/number-input";
</script>

<template>
  <NumberInputRoot defaultValue="1" :min="0" :max="10">
    <NumberInputLabel>Quantity</NumberInputLabel>
    <NumberInputControl />
  </NumberInputRoot>
</template>

// src/components/demos/react/number-input.tsx
import {
  NumberInputRoot,
  NumberInputLabel,
  NumberInputControl,
} from "@/components/ui/number-input";

function NumberInputDemo() {
  return (
    <NumberInputRoot defaultValue="1" min={0} max={10}>
      <NumberInputLabel>Quantity</NumberInputLabel>
      <NumberInputControl />
    </NumberInputRoot>
  );
}

export { NumberInputDemo };
