// src/components/demos/react/datepicker.tsx
import {
  DatePickerRoot,
  DatePickerControl,
  DatePickerContent,
  DatePickerCalendar,
} from "@/components/ui/date-picker";

function DatepickerDemo() {
  return (
    <DatePickerRoot>
      <DatePickerControl />
      <DatePickerContent>
        <DatePickerCalendar />
      </DatePickerContent>
    </DatePickerRoot>
  );
}

export { DatepickerDemo };

// src/components/demos/vue/datepicker.vue
<script setup lang="ts">
import {
  DatePickerRoot,
  DatePickerControl,
  DatePickerContent,
  DatePickerCalendar,
} from "@/components/ui-vue/date-picker";
</script>

<template>
  <DatePickerRoot>
    <DatePickerControl />
    <DatePickerContent>
      <DatePickerCalendar />
    </DatePickerContent>
  </DatePickerRoot>
</template>
