// src/components/ui-vue/portal.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

// Astro server-renders islands, and Teleport needs a real `document` to move
// into. Stay `disabled` (render inline) until mounted on the client, then
// teleport — mirrors the React Portal's server/client split.
const mounted = ref(false);
onMounted(() => (mounted.value = true));
</script>

<template>
  <Teleport to="body" :disabled="!mounted">
    <slot />
  </Teleport>
</template>

// src/components/ui/portal.tsx
import { useSyncExternalStore } from "react";
import { createPortal } from "react-dom";

const subscribe = () => () => {};

/**
 * Renders children into document.body on the client, and inline on the server.
 *
 * The server check matters: Astro server-renders islands, and `createPortal`
 * needs a real `document`.
 */
function Portal({ children }: React.PropsWithChildren) {
  const isServer = useSyncExternalStore(
    subscribe,
    () => false,
    () => true
  );

  if (isServer) return <>{children}</>;

  return createPortal(children, document.body);
}

export { Portal };
